apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels: 
        app: techtrends
    spec:
      containers:
      - image: anandbelagurki/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends-latest
        ports:
          - containerPort: 3111
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /
            port: 3111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"